### ISSUE TITLE
Selected item no longer working in 4.0.2 

### ISSUE THREAD

**Issue by HarborIntex** [akgulebubekir/Maui.DataGrid#170]
I updated by project to the latest stable 4.0.2 and all my grids lost the ability to select items.
After testing and debugging - I downloaded the full 4.0.2 code ZIP and ran the sample and it also is not working in the sample.
Tested with Android local device and emulator.

Anyone else?

**Comment by andreptcosta** [comment]
same problem here

**Comment by symbiogenesis** [comment]
Try setting the <MauiVersion> to 8.0.6

**Comment by symbiogenesis** [comment]
Fixed with #171

**Comment by lendres** [comment]
This is fantastic, thanks for the fix.  I've downloaded, compiled, and tested this update with 8.0.20 and the selection seems to be working.

**Comment by andreptcosta** [comment]
@lendres I tried using 8.0.20 and 4.0.3 and it still doesn't work. I ran the test project and it didn't work either. What did you do differently?

**Comment by andreptcosta** [comment]
@HarborIntex Can you check if the problem has been fixed? I updated to 4.0.3 with MAUI 8.0.20 and ItemSelected still doesn't fire

**Comment by lendres** [comment]
> @lendres I tried using 8.0.20 and 4.0.3 and it still doesn't work. I ran the test project and it didn't work either. What did you do differently?

I downloaded the repo and compiled it.  I just tried it by installing 4.0.3 from NuGet and it does seem to be working for me.  I tested the sorting and that the selected item was correctly printed to the output window.  That is, from the demo, the function in MainViewModel.cs
```csharp
    private void CmdTapped(object item)

    {
        if (item is Team team)
        {
            Debug.WriteLine($"Item Tapped: {team.Name}");
        }
    }
```
correctly prints the selected item.  I'm not sure what you mean by "ItemSelected still doesn't fire."  Is that specific to your code or in the demo app?

**Comment by andreptcosta** [comment]
@lendres There is the ItemSelected eventhandler in DataGrid, where the selected item function worked until 4.0.1.

Yes RowTappedCommand works but EventHandler ItemSelected does not

**Comment by lendres** [comment]
I hooked onto the ItemSelected event and it triggers.

If you feel it is not working, I'd suggest posting a separate issue with a minimum working example.

**Comment by HarborIntex** [comment]
> @HarborIntex Can you check if the problem has been fixed? I updated to 4.0.3 with MAUI 8.0.20 and ItemSelected still doesn't fire

Sorry got pulled onto another project last week and this sat on the burner.
Upgraded and no - I am getting the same thing as you - my ItemSelected does not fire.

In my code behind of my form I simply have:
 grdPallets.ItemSelected += grdPallets_ItemSelected;

private void grdPallets_ItemSelected(object sender, EventArgs e)
{
   // do cool stuff.
    
}


This worked fine up to 4.0.1 - but no longer.
I see @lendres says it works for him.  Can you show your code?

I can change my code to RowTappedCommand - but if the ItemSelected trigger still works - I would prefer to just correct my existing code.

**Comment by akgulebubekir** [comment]
@HarborIntex  I've created 2 unit test cases to make sure its working properly. So far I couldn't reproduce. Please let us know if you can.

**Comment by lendres** [comment]
I cannot reproduce it either.  I've tested it by hooking it up from both the xaml and code-behind and both work for me.  I think it would be best to post a minimum working example where you are having the issue.

**Comment by HarborIntex** [comment]
[DGSelectedItemTest.zip](https://github.com/akgulebubekir/Maui.DataGrid/files/15131350/DGSelectedItemTest.zip)

Attached is VERY simple test application.   In 4.0.1 the ItemSelected event fires.  Upgrade to 4.0.3 and it does not.
![image](https://github.com/akgulebubekir/Maui.DataGrid/assets/106819966/77808edf-5204-411f-8fc3-4ecfe5798cae)

Here is he code behind for the main form.

The only thing I change from version to version is:
SelectionEnabled="True" to SelectionMode="Single"

using System.Data;
using DGSelectedItemTest.ViewModels;

namespace DGSelectedItemTest
{
    public partial class MainPage : ContentPage
    {

        public MainPage()
        {
            InitializeComponent();
            grdTest.ItemSelected += GrdTest_ItemSelected;

            DataSet ds = new DataSet();
            DataTable dt = new DataTable();
            DataRow dr = dt.NewRow();
            DataColumn  dc = new DataColumn();

            dc.ColumnName = "Test";
            dc.DefaultValue = "Testing";
            dt.Rows.Add(dr);
            dt.Columns.Add(dc);
            ds.Tables.Add(dt);

            BindingContext = new TestViewModel(ds);
   
        }

        private void GrdTest_ItemSelected(object? sender, SelectionChangedEventArgs e)
        {
            DisplayAlert("Simple DG Test", "Works with 4.0.1", "Ok");
        }

       
    }

}

**Comment by lendres** [comment]
I tested your code as you uploaded it with only one change, I used a "Windows Machine" (I don't have a working Android emulator installed) and it work (DataGrid v4.0.3, Maui Controls 8.0.21).

If you are able to test on a Windows platform, could you please try that and see if there is a difference?

![datagrid-test](https://github.com/akgulebubekir/Maui.DataGrid/assets/8999134/8d08638d-424b-4cf2-b08d-814e5c29ece5)

**Comment by HarborIntex** [comment]
Thanks for testing.
It does work for Windows - but also does **not** work with Android Emulator (Pixel 5 api 33)

**Comment by HarborIntex** [comment]
@symbiogenesis @lendres either of you able to recreate this with Android with my example?  I see the "solution" to 176 above was to rollback to .01.  I don't want to do that.  Can this not be reopened?  

Again - my example is as simple as you can get and does not work on Android native or Emulator.  Windows does work - but I have no need for that.

**Comment by lendres** [comment]
@HarborIntex This issue was originally for the selected item which has been fixed and so the issue was closed.  I would suggest submitting this as a new issue and including your example for Windows and Android.

**Comment by symbiogenesis** [comment]
@HarborIntex  There were a lot of problems with your sample app. But after correcting all of them, there was still a problem.

This PR: https://github.com/akgulebubekir/Maui.DataGrid/pull/163 introduced RowTappedCommand via a gesture recognizer

If I remove that gesture recognizer and then run your sample app, then it works.

So, for now, until a hotfix is released, I recommend using a project reference to the DataGrid project. And then just remove the following lines from the DataGrid XAML code of this library:

```xaml
<local:DataGridRow.GestureRecognizers>
    <TapGestureRecognizer Command="{Binding RowTappedCommand, Source={x:Reference self}}" CommandParameter="{Binding .}" />
</local:DataGridRow.GestureRecognizers>
```

**Comment by symbiogenesis** [comment]
Here were the biggest errors with your app, for your own future reference:

- The SelectedItem was set the same as the ItemsSource. Instead, you should have a single SelectedTestItem property and a TestItems collection

- The DataType annotation on the CellTemplate was wrong. It should have been set to the TestItem object, not the ViewModel. And the binding of the label should've been set to the Test property.

**Comment by symbiogenesis** [comment]
@HarborIntex also you don't need to open another issue, because someone already had opened one that pinpointed the issue

https://github.com/akgulebubekir/Maui.DataGrid/issues/175

**Comment by HarborIntex** [comment]
Works with 4.04 with no changes - thank you!
